### ISSUE TITLE
upgrade to sbt 1 and latest scalafmt?

### ISSUE THREAD

**Issue by SethTisue** [suzaku-io/boopickle#104]
I am adding boopickle to the Scala 2.12 community build (https://github.com/scala/community-builds/pull/788), but dbuild can't deal with the version of scalafmt in your build

for now I have forked boopickle to remove scalafmt entirely, and that's okay, but it would be nicer if you moved to sbt 1 and to this version of sbt-scalafmt: https://scalameta.org/scalafmt/docs/installation.html#sbt-scalafmt

**Comment by ochrons** [comment]
Sounds doable :)

**Comment by ochrons** [comment]
Now using SBT 1.2.3 and latest scalafmt

**Comment by SethTisue** [comment]
thank you Otto! scala/community-builds@de635ff1fed1aabe5a5b2cccfe353e938313f47a
