### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by mathieuleclaire** [suzaku-io/boopickle#120]
Is this lib still maintained ? If not, could you invite some of us as collaborators so that we can merge PR and continue publishing it ?

**Comment by japgolly** [comment]
+1

**Comment by japgolly** [comment]
+1 - happy to help maintain

**Comment by ochrons** [comment]
Yeah, contributors are welcome! I'm currently quite busy being the CEO of my startup, so not much time for maintaining OSS libs 😅

**Comment by mathieuleclaire** [comment]
Great. I am volunteer to give a hand. I guess @japgolly and @tbje would be too !?
Just out of curiosity, what kind of company are you building?

**Comment by ochrons** [comment]
E-bike tech company https://revonte.com :)

**Comment by mathieuleclaire** [comment]
Woo, impressive ! Boopickle does not seem to be the core application :) !
Thanks for the invitation.

**Comment by ochrons** [comment]
We do use Scala for our backend services, though, and I'm still writing some code when I have time 😉

**Comment by japgolly** [comment]
Thanks @ochrons.

Also re revonte fantastic to hear, it looks awesome! Good luck with that mate.
