### ISSUE TITLE
Release for scala.js 1.0

### ISSUE THREAD

**Issue by cquiroz** [suzaku-io/boopickle#123]

**Comment by mathieuleclaire** [comment]
If your question was "Could you please release a version compatible with scalajs 1.0 ?", it is done already (1.3.2).

**Comment by cquiroz** [comment]
Yes, sorry for not being more explicit. I got confused

**Comment by strelec** [comment]
1.3.2 has a broken build when using Scala 2.12. Only Scala 2.13 is supported.
