### ISSUE TITLE
Troubles with 1.3.2 release

### ISSUE THREAD

**Issue by cquiroz** [suzaku-io/boopickle#124]
It seems there are some troubles. Maybe the jvm side jar was built with a newer jdk and that is causing troubles at http4s
https://github.com/http4s/http4s/pull/3424

Could it be possible to cut a new release?

**Comment by slandelle** [comment]
That's exactly what I predicted [here](https://github.com/suzaku-io/boopickle/issues/117#issuecomment-627600948).

I described an easy fix [here](https://github.com/suzaku-io/boopickle/issues/117#issuecomment-627610200).
