### ISSUE TITLE
Release 1.3.3

### ISSUE THREAD

**Issue by japgolly** [suzaku-io/boopickle#127]
To summarise, there were two problems with the 1.3.2 release:
* Compiling with JDK 11 broke users on JDK 8
* Dirty Scala.JS 0.6.x artifacts were included in the Scala 1.x jars

And remedies:
* Merged a PR for the JDK problem
* I've cleared the Travis CI caches for boopickle just in case. Otherwise @ochrons please take care to include a clean when building (or maybe even delete `target` dirs manually - although sbt clean has always been enough for my releases with cross SJS and cross Scala versioning :man_shrugging: )

@ochrons can you please do another release :pray:

**Comment by japgolly** [comment]
Alternatively @ochrons  if you're ok to hand over or lend out the sonatype credentials to me, I'd be happy to do the release.

**Comment by ioleo** [comment]
@ochrons is there some blocker for this, or you simply did not have time to look into it? Don't mean to rush you, I'm just curious as I have one project "on hold" waiting for this (and some upstream libs that depend on boopickle).

**Comment by japgolly** [comment]
To those interested, yesterday I published a release of 1.3.3 using my own account under `com.github.japgolly.fork.boopickle` instead of `io.suzaku`. Feel free to use it until the proper 1.3.3 release gets sorted out.

**Comment by ochrons** [comment]
Got the Github Actions working now and a 1.3.3 release is pushed. Thanks to @cquiroz for helping with CI!

**Comment by japgolly** [comment]
Even better! Thank you both!
