### ISSUE TITLE
Pickle Map with Any as value

### ISSUE THREAD

**Issue by manosntoulias** [suzaku-io/boopickle#140]
Is there a way to pickle a Map with Any as its value? I suppose the key that is a String is not a problem.

Error:(36, 36) Cannot materialize pickler for non-case class: Map[String,Any]. If this is a collection, the error can refer to the class inside.
      val buffer = Pickle.intoBytes(map)

**Comment by ochrons** [comment]
Nope. Only values that have a known type at compile time can be pickled/unpickled. This is because Boopickle stores no information about the types in its encoding, so the decoder also must know the types that its decoding.
