### ISSUE TITLE
Scala 3 pickle format is not compatible with Scala 2 format

### ISSUE THREAD

**Issue by strelec** [suzaku-io/boopickle#183]
Imagine a scenario:

1. Backend on Scala 2
2. Frontend (scala.js) on Scala 3

It appears that we get a decoding error, similar to this:

```
[error] Caused by: java.lang.IllegalStateException: Index 46 is not defined in this CompositePickler
[error] 	at boopickle.CompositePickler.unpickle(CompositePicklers.scala:39)
[error] 	at boopickle.PicklerHelper.read(Pickler.scala:51)
[error] 	at boopickle.PicklerHelper.read$(Pickler.scala:40)
[error] 	at boopickle.BasicPicklers$.read(Pickler.scala:54)
```

**Comment by FlorianKirmaier** [comment]
I think you should provide a class hierarchy, with a description of how you create the "picklers". 
Otherwise, no one can help you.
My first guess would be, that macro-generated picklers behave differently (if they still work with scala3).

**Comment by strelec** [comment]
I think the difference is how value classes are serialized (extends AnyVal).

**Comment by strelec** [comment]
Figured it out. Minimal ex\mple:

```scala
case class B(p1: Seq[Int])
Pickle.intoBytes(B(Seq(10, 20, 30, 40)))
```

Scala3 does not output the extra zero at the begining:

Scala 2: `0, 4, 10, 20, 30, 40`
Scala 3: `4, 10, 20, 30, 40`

**Comment by strelec** [comment]
Actually, I changed my mind.

I find the Scala 3 format much better. It is about 20-30 percent more efficient, due to skipping of those useless zero bytes.

Let's keep the Scala 3 format, as it is more efficient and easier to write custom decoders. Scala 2 is going to be phased out soon enough.
