### ISSUE TITLE
Is binary format сompatible with MessagePack?

### ISSUE THREAD

**Issue by RicoGit** [suzaku-io/boopickle#189]
Which binary format used for serialization? Docs says that "BooPickle borrows heavily from both uPickle", which implements MessagePack binary format. It's the same for Boopickle? Could I deserialize binary message from Boopickle from other language?

**Comment by FlorianKirmaier** [comment]
No, deserializing from another language is very complicated - it's basically a dynamically created binary format.
It doesn't have any guarantee to be compatible with anything - except with itself. This has the advantage that the implementation is very optimized and therefore very fast and small.

**Comment by slandelle** [comment]
The encoding is similar to msgpack’s and protobuf’s but not identical, so it’s not compatible.

**Comment by RicoGit** [comment]
Thank you guys!

**Comment by strelec** [comment]
I have noticed that the binary format is not even compatible within the library. Scala 3 and Scala 2 formats are incompatible. Why is this so, and is it intended?

https://github.com/suzaku-io/boopickle/issues/183
