### ISSUE TITLE
Is this compatible with scala 2.10?

### ISSUE THREAD

**Issue by r4ravi2008** [suzaku-io/boopickle#70]

**Comment by ochrons-umbra** [comment]
I haven't made any effort towards 2.10, so it might work, or it might now. Feel free to experiment :)

**Comment by ochrons** [comment]
I haven't made any effort towards 2.10, so it might work or might not. Feel free to experiment :)

**Comment by ochrons** [comment]
Scala 2.10 support is being withdrawn on many projects now that SBT is moving to Scala 2.12 so closing this too,
