### ISSUE TITLE
ByteBuffer to JavaScript bytes

### ISSUE THREAD

**Issue by Tamriel** [suzaku-io/boopickle#71]
At the section 'Using ByteBuffers in network communication' of the documentation you write:
> On the JS side things are a bit more complicated due to the use of JavaScript ArrayBuffer underneath the ByteBuffer.

I would like to see an example!

**Comment by ochrons** [comment]
It's in the Scala.js library source codes :)

**Comment by Tamriel** [comment]
It would be nice if you provide a link to the file + line you have in mind in the documentation.
