### ISSUE TITLE
Scala.js 1.0.0-M1 support

### ISSUE THREAD

**Issue by sherpal** [suzaku-io/boopickle#77]
It would be much appreciated if you could add support for Scala.js 1.0.0-M1.
Thank you very much, love your work!

**Comment by ochrons** [comment]
This is on the TODO list, but currently it's pending on dependencies like utest and nyaya being available for 1.0.0-M1.

**Comment by ochrons** [comment]
This is now implemented in the master branch, but no new version has yet been released. Feel free to try it out locally!

**Comment by sherpal** [comment]
I tried it and it works like a charm! Thank you.
