### ISSUE TITLE
Remove PicklerGenerator in DefaultBasic object

### ISSUE THREAD

**Issue by cornerman** [suzaku-io/boopickle#88]
In the `Default` object, we have the implicit method `generatePickler` directly available. Differently, the `DefaultBasic` object has [an inner object `PicklerGenerator` with a `generatePickler` method](https://github.com/suzaku-io/boopickle/blob/master/boopickle/shared/src/main/scala/boopickle/Default.scala#L156). I find this little difference cumbersome when switching between import Default and DefaultBasic in a file, sometimes it needs `import PicklerGenerator._`, sometime not.

Can we remove the `PicklerGenerator` object and move the method into the `DefaultBasic` object?

**Comment by ochrons** [comment]
Yeah, I'm not sure if there was a reason for this, or if it's just some historical artifact. Probably the latter, so I'm open to unifying them :)
