### ISSUE TITLE
boopickle example of using with javascript and websockets

### ISSUE THREAD

**Issue by jiteshsharma** [suzaku-io/boopickle#90]
Hello,

I know this is not an issue with the code, but is there a simple example somewhere of Serializing a case class using BP, sending it over a websocket and then DeSerializing it in the javascript? I am assuming this would be a common use case, but can not find any example code or documentation anywhere.

Thanks,
Jitesh

**Comment by ochrons** [comment]
You could ask on the BooPickle [Gitter channel](https://gitter.im/suzaku-io/boopickle) if anyone is doing that, Personally I have not :)
